export const API_ERROR_CODES = {
  AUTH: {
    LOCAL_EMAIL_ALREADY_TAKEN: 'AUTH_LOCAL_EMAIL_ALREADY_TAKEN',
    INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    INVALID_ACCESS_TOKEN: 'AUTH_INVALID_ACCESS_TOKEN',
  },
  ACCOUNT: {
    NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  },
  TRACK: {
    PROVIDER_UNAVAILABLE: 'TRACK_PROVIDER_UNAVAILABLE',
  },
  PLAYLIST: {
    NOT_FOUND: 'PLAYLIST_NOT_FOUND',
    INVALID_TRACK_REFERENCE: 'INVALID_PLAYLIST_TRACK_REFERENCE',
  },
} as const;
