export const API_ERROR_CODES = {
  AUTH: {
    LOCAL_EMAIL_ALREADY_TAKEN: 'AUTH_LOCAL_EMAIL_ALREADY_TAKEN',
    INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  },
  USER: {
    NOT_FOUND: 'USER_NOT_FOUND',
  },
} as const;
