name: pupufy-app

services:
  db:
    image: postgres:18
    container_name: pupufy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: pupufy_app
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pupufy
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

  api:
    image: pupufy-api:test
    container_name: pupufy-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db

  web:
    image: pupufy-web:test
    container_name: pupufy-web
    restart: unless-stopped
    ports:
      - '8080:80'
    depends_on:
      - api

volumes:
  postgres_data:
