import type { DeveloperInfo } from '~/pages/about-us/models/developer.model';

export const DEVELOPERS: DeveloperInfo[] = [
  {
    name: 'Anastasia',
    fullName: 'Anastasia Savrukhina',
    id: 'anastasia',
    description:
      'I thought the hardest part of the project would be the application architecture. Then there was CSS.',
    githubLink: 'https://github.com/savryna',
    imgUrl: 'https://avatars.githubusercontent.com/u/123760669?v=4',
    badge: ['UI/UX', 'Frontend', 'Backend'],
    responsibilities: [
      'Figma mockup',
      'Application navigation and header',
      'Reusable UI components',
      'Artist, Album, Library, and About Us pages',
      'Playlist creation and editing',
      'NgRx Signal Store',
      'Backend endpoint integration',
      'Code Review',
    ],
    stacks: ['Angular', 'NgRx', 'Figma', 'NestJs', 'RxJs'],
  },
  {
    name: 'Hanna',
    fullName: 'Hanna Surmach',
    id: 'hanna',
    description: '"World\'s best boss" - I think that pretty much sums it up',
    githubLink: 'https://github.com/khasekai',
    imgUrl: 'https://avatars.githubusercontent.com/u/58516288?v=4',
    badge: ['Team Lead', 'Mentoring'],
    responsibilities: [
      'Team mentoring',
      'Task planning and distribution',
      'Technical guidance',
      'Learning materials preparation',
      'Trello management',
      'Code Review',
    ],
  },
  {
    name: 'Nikita',
    fullName: 'Nikita Melnikov',
    id: 'nikita',
    description:
      'Creates the best endpoints, possibly ever. Very secure, very scalable, very lightly documented. And that is not him saying it. People are saying it. Very smart people. The best people. They look at the code, they look at the speed, and they say, “Nobody ships like this guy. Nobody.”',
    githubLink: 'https://github.com/tryproxy',
    imgUrl: '/img/trypoxy-img.jpg',
    badge: ['Frontend', 'Infrastructure', 'Backend'],
    responsibilities: [
      'Backend architecture and core API setup',
      'Database design and Prisma schema',
      'Swagger setup',
      'Infrastructure and deployment setup',
      'Authentication and session management',
      'Reusable UI component',
      'Registration, Login and Discovery page',
      'User track upload',
      'Code Review',
    ],
    stacks: ['Angular', 'RxJs', 'NestJs', 'Docker', 'Prisma', 'PostgreSQL', 'Swagger'],
  },
  {
    name: 'Vsevolod',
    fullName: 'Vsevolod Timoshenko',
    id: 'vsevolod',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt ducimus esse est ex in neque non quis ' +
      'rerum tempora voluptatibus?',
    githubLink: 'https://github.com/shoblinsky',
    imgUrl: 'https://avatars.githubusercontent.com/u/123806946?v=4',
    badge: ['Frontend', 'Backend', 'Testing'],
    responsibilities: [
      'Reusable search bar with autocomplete',
      'Search, 404 page',
      'Music player widget',
      'Playback queue component',
      'Recently played queue',
      'Toast notification service',
      'Unit testing setup',
      'Backend endpoint integration',
      'Code Review',
    ],
    stacks: ['Angular', 'RxJs', 'Vitest', 'NestJs'],
  },
];
