export const TRACKS_CONFIG = {
  DISCOVERY: {
    REQUEST_TRACK_LIMIT: 10,
    REQUEST_MAX_ATTEMPTS: 5,
    RETRY_REQUEST_DELAY_MS: 200,
  },
  SEARCH: {
    //
    REQUEST_MAX_ATTEMPTS: 3,
    RETRY_REQUEST_DELAY_MS: 200,
  },
};
