FROM node:24-alpine AS build

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@10.33.2 --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml nx.json tsconfig.base.json prisma.config.ts ./
COPY apps ./apps
COPY packages ./packages

RUN pnpm install --frozen-lockfile
RUN pnpm prisma generate
RUN pnpm nx build api

FROM node:24-alpine

WORKDIR /app

ENV NODE_ENV=production

RUN corepack enable && corepack prepare pnpm@10.33.2 --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml prisma.config.ts ./
RUN pnpm install --prod --frozen-lockfile --ignore-scripts
RUN pnpm prisma generate

COPY --from=build /app/dist/apps/api ./

EXPOSE 3000

CMD ["node", "main.js"]
